import = ["~/.nix-profile/catppuccin.toml"]
[font]
size = 16
[font.bold]
family = "Fira Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Fira Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Fira Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Fira Mono Nerd Font"
style = "Regular"

[shell]
program = "tmux"
